CSEG
mov cl, 32h
lea dx,char1
int 224

mov cl, 32h
lea dx,char2
int 224

mov cl, 32h
lea dx,char3
int 224

mov cl, 32h
lea dx,char4
int 224

mov cl, 32h
lea dx,char5
int 224

mov cl, 32h
lea dx,char6
int 224

mov cl, 32h
lea dx,char7
int 224

mov cl, 32h
lea dx,char8
int 224

DSEG
org 100h
char1  db   4h,'H',0,0,0
char2  db   4h,'I',0,0,0
char3  db   4h,' ',0,0,0
char4  db   4h,'B',0,0,0
char5  db   4h,'I',0,0,0
char6  db   4h,'O',0,0,0
char7  db   4h,'S',0,0,0
char8  db   4h,'!',0,0,0
end

